### ISSUE TITLE
Requests icons when adding requests are the old ones

### ISSUE THREAD

**Issue by msaug** [Hexanax/PLD-Agile#23] opened 2021-11-01 16:19 UTC
Steps to reproduce : 
Open app
Load map
Load request set
Add a new request

Result : 
The requests read from the XML file are displayed on the map with the new icons, whereas the added requests is still displayed with the old icon

**Comment by rbelateche** [comment] 2021-11-01 17:32
I think the issue is resolved now that I have merged my branch, could you confirm please ? Thanks.

**Comment by M4TTRX** [comment] 2021-11-01 18:38
While the depot uses an old icon because Rayane was too lazy to figure a way to have his stuff work and use my icons, this issue seems to be gone with the latest commit.

**Closed by M4TTRX** 2021-11-01 18:38 UTC
